spring.application.name=pgmanagement
server.port=8081

# Enable or disable cache for Thymeleaf templates
spring.thymeleaf.cache=false

# Set prefix and suffix for Thymeleaf templates
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/pg_management
spring.datasource.username=postgres
spring.datasource.password=tad

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# application.properties
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


#Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aranjith225@gmail.com
spring.mail.password=faozjtehyawqwqzm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.main.allow-circular-references=true
debug=true

logging.level.org.springframework.security=DEBUG
